## Functions

A function is a block of code that performs a specific taks and is only executed when it is called from somewhere else inside your program. You typically create functions when certain tasks have to be executed several times. So as a general rule, when you're programming and you find that you are repeating the same lines of code twice or more, then it is time to think about bundling them into a function. This leaves less room for errors and it makes your code much easier to read and understand. Moreover, it is less work to change the function than it is to change the code in all the places where repetition occurs.

The code block below demonstrates how a function is defined. The first line starts with `def`, which tells Python that you plan to define a function. After `def` comes the name of the function, `describe_person` in this case. After the function name come parentheses. In this example, the word `name` appears between parentheses, meaning that the function `describe_person` accepts an *argument*, which in this case is called `name`. Effectively, `name` is a variable that will be available inside (and only inside) the function. Note that the line with the function definition must end with a colon, and that all code that belongs to the function must be indented.

In [ ]:
def describe_person(name):
    if name == "Vincent":
        print("Vincent is one of the instructors of the Python Masterclass")
    elif name == "Anushree":
        print("Anushree is the AWS support person during the Python Masterclass")
    else:
        print("Name is unknown, not sure what message to print for this person.")

The function contains a series of conditional statements that check the value of `name` and print a certain message to the screen depending on the name provided. Calling the function (this is programming terminology for executing the function) is done in the following way

In [ ]:
describe_person("Vincent")

It is not compulsory for a function to accept arguments, so the following function definition is fine as well

In [ ]:
def func_without_args():
    print("This function does not accept arguments")

To execute the function it needs to be called like this

In [ ]:
func_without_args()

When you call a function without parentheses it only shows a reference to the function.

In [ ]:
func_without_args

***Exercise 1***: Add your own description to the function definition of `describe_person()`. Then call the function with your name as the argument.

In [19]:
# Modify the code below
def describe_person(name):
    if name == "Vincent":
        print("Vincent is one of the instructors of the Python Masterclass")
    elif name == "Anushree":
        print("Anushree is the AWS support person during the Python Masterclass")
    elif name == "Gabriel":
        print("Gabriel is a student of the Pythoon Masterclass")
    else:
        print("Name is unknown, not sure what message to print for this person.")

name_to_check= "Gabriel"
msg = "input= " + name_to_check  + r" "+ str(describe_person(name_to_check))
print(msg)

Gabriel is a student of the Pythoon Masterclass
input= GabrielNone


A function can also return a value. For example

In [ ]:
def describe_person(name):
    if name == "Vincent":
        rv = "Vincent is one of the instructors of the Python Masterclass"
    elif name == "Anushree":
        rv = "Anushree is the AWS support person during the Python Masterclass"
    else:
        rv = "Name is unknown, not sure what message to print for this person."
    
    return rv

Now it can be called in the following way

In [ ]:
msg = describe_person("Anushree")
print(msg)

A function can have multiple arguments. It can also have optional arguments, which are called *keyword arguments* (or simply *kwargs*) in Python. A keyword argument is defined by specifying a default value within the function definition. In the example below `age` becomes a keyword argument because a default value of 23 years is assigned to it using the equal sign.

In [ ]:
def describe_person(name, age=23):    
    return f"{name} is {age} years old."

Note that in the above code, use is made of a formatted string. It can be recognised by the `f` that precedes the first double quote of the string. In a formatted string, any variable enclosed between curly brackets (in this case `name` and `age`) will be substituted by its value.

The function can now be called like this

In [ ]:
msg = describe_person("Vincent", 29)
print(msg)

Or like this

In [ ]:
msg = describe_person("Anushree")
print(msg)

Note that keyword arguments must always come after non-keyword arguments, otherwise Python will throw an error.

***Exercise 2***: Add the keyword argument `nationality` to the `describe_person()` function. Use the argument in your function and call the function.

In [25]:
# Modify the code below
def describe_person(name, age=18, nationality = "Aussie") :    
    return f"{name} is {age} years old | Nationality: {nationality}"

#-----------------------------------------------------
Name= "Gabriel"
Age=31
Nationality= "Colombian"

print(describe_person(Name,Age,Nationality))
#-----------------------------------------------------
Name= "Nelson"
print(describe_person(name=Name))



Gabriel is 31 years old | Nationality: Colombian
Nelson is 18 years old | Nationality: Aussie


In [26]:
Name= "Gabriel"
Age=31
Nationality= "Colombian"
print(describe_person(Name,Age,Nationality))


Gabriel is 31 years old | Nationality: Colombian


## Docstrings
It is common practice to document the behaviour of a function using a so-called *docstring*. First of all, a docstring should describe what the function's purpose is. Then it provides information about the arguments (or parameters) that must/can be passed to the function, and the value that the function returns.

In [ ]:
def describe_person(name, age=23):
    """
    This function returns a message with a persons name and age.
    
    Parameters
    ----------
    name : str
        A string with the name of the person.
    age : int, optional
        An integer with the person's age in years. Default: 23.
        
    Returns
    -------
    result : str
        A string containing the message.
    """
    return f"{name} is {age} years old."

Suddenly our code got a lot longer and the time involved in creating good docstrings should not be underestimated. But they are an essential part of good coding practice because they allow others to understand what the function does. This includes the users of your program, other developers and yourself when you return to a piece of code several years after you last worked on it.

The style used in the code cell above follows the convections for the <A href="https://numpydoc.readthedocs.io/en/latest/format.html">numpydoc extension for Sphinx</A>. Sphinx is a tool that creates the documentation of your code project partially based on the docstrings you have provided, so writing good docstrings can save you lots of time later on when you want to share your code with others.

The docstring also serves to provide interactive help about a function within an IDE, or a notebook environment. For example, in Jupyter notebook or Jupyter lab, we can now get help on our function by typing

In [ ]:
describe_person?

or

In [ ]:
help(describe_person)

In an IDE, typing the function name followed by the opening parenthesis genereally results in a window popping up with the docstring. In a workbook environment you can try the function name followed by the opening parenthesis and then hitting Shift + Tab (from experience this does not work in all cases, but give it a try in the code cell below)

In [ ]:
describe_person( # Place your cursor after the opening parenthesis and hit Shift + Tab to display the docstring

## Checking arguments

The following function calculates the square of $x$ when $x <= 0$ and the square root of $x$ when $x > 0$ (not sure when you'd ever need this but it is just an example)

In [ ]:
import numpy as np

def funky_function(x):
    if x <= 0:
        return x ** 2
    else:
        return np.sqrt(x)

Printing the result for $x = -10$ and $x = 10$ demonstrates that it works

In [ ]:
print(funky_function(-10))
print(funky_function(10))

But what if we pass an array to the function? This results in an error because of the `if` statement

In [10]:
x = np.linspace(-10, 10, 3)
print(x)
funky_function(x)

[-10.   0.  10.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

To avoid such things from happening, it is important to add some code to your function that checks the type of x and rewrite the function in such a way that it will work both when `x` is a scalar and an array. There could be multiple ways to do this, for example

In [11]:
def funky_function(x):
    x = np.atleast_1d(x)
    rv = np.empty_like(x)
    idx = x <= 0
    rv[idx] = x[idx] ** 2
    rv[~idx] = np.sqrt(x[~idx])
    
    return rv

Now let's try the code that did not work before

In [12]:
x = np.linspace(-10, 10, 3)
funky_function(x)

array([100.        ,   0.        ,   3.16227766])

and also try it with a scalar `x`

In [13]:
funky_function(10)

array([3])

That worked! Or did it? Is the square root of 10 really 3? Well, almost but what happened here is that NumPy rounded the result of the `sqrt` function to the nearest whole number. Why would it do that, since it is clearly wrong?! The answer has to do with variable types. In this case we passed 10, which is an integer. The number got converted to an array with NumPy's `atleast_1d` function, from which the array with the return values was derived using the `empty_like` function. Because the function's input argument `x` was an integer, both arrays end up being integer arrays and the numbers they contain will remain integers, even when you assign a float to an element.

This shows that writing functions can be very tricky and that you should always verify that their result is what you intended under the widest range of conceivable circumstances (there are in fact special techniques for this, which are known as unit testing). Now let's solve this issue by ensuring that `rv` is an array of floats, simply by adding `dtype=float` when we create it.

In [14]:
def funky_function(x):
    x = np.atleast_1d(x)
    rv = np.empty_like(x, dtype=float)
    idx = x <= 0
    rv[idx] = x[idx] ** 2
    rv[~idx] = np.sqrt(x[~idx])
    
    return rv

In [ ]:
funky_function(10)

***Exercise 3***: Now we want to slightly modify the function so that it returns a scalar when the argument $x$ was also a scalar (and not an array). *Hint*: you can use the `len(rv)` function to check the number of elements in `rv`.

In [ ]:
# Modify the code below

def funky_function(x):
    x = np.atleast_1d(x)
    rv = np.empty_like(x, dtype=float)
    idx = x <= 0
    rv[idx] = x[idx] ** 2
    rv[~idx] = np.sqrt(x[~idx])
    
    return rv

Does this mean we are done now? Not quite. What if a user calls our function and accidentally passes a string variable rather than a number?

In [ ]:
funky_function('ten')

Obviously that didn't work. If this were a real function that was being used inside a `for` loop for example, the program would crash. As a programmer you have to think of ways to prevent such things from happening. One way would be to embed the code inside the function between `try` and `except` statements. The code under `try` gets executed but when an error occurs, Python jumps to the `except` part where you can specify what needs to happen in that case. In this example, it probably makes most sense to issue some sort of warning and return an empty return value, which is available in Python as `None'

In [ ]:
def funky_function(x):
    try:
        # The code lines below are the same as before
        x = np.atleast_1d(x)
        rv = np.empty_like(x, dtype=float)
        idx = x <= 0
        rv[idx] = x[idx] ** 2
        rv[~idx] = np.sqrt(x[~idx])

        return rv
    except:
        print("Warning: an error occurred. Check input argument.")
        return None

Now let's try if it worked by embedding the function inside a `for` loop

In [ ]:
for x in [-10, 0, 10, 'ten']:
    y = funky_function(x)
    print(y)

Finally, let's have a look at how we can set up the code within the for loop to ensure that our program does not crash when we try to add the first element of the array `y` to a list. Since we know that `funky_function` returns `None` when an error occurred, and an array otherwise, we can check for this condition, and only add the first element of `y` when `y` is not `None`.

In [ ]:
meaningful_results = []
for x in [-10, 0, 10, 'ten']:
    y = funky_function(x)
    if y is not None:
        meaningful_results.append(y[0])

print(meaningful_results)

Checking for errors can be a lot of work and require lots and lots of lines of code. Nonetheless it should become an integral part of your coding as the potential for incorrect results is enormous.